robots:
  - id: CAR
    def: CAR
    interaction_distance: 2

objects:
  - id: FRONT_CRATE
    def: FRONT_CRATE
    pick_target: true
    place_target: false

  - id: MEDICINE_BOTTLE
    def: MEDICINE_BOTTLE
    pick_target: true
    place_target: false

  - id: TEMP_ZONE
    def: TEMP_ZONE
    pick_target: false
    place_target: true

  - id: MEDICAL_TABLE
    def: MEDICAL_TABLE
    pick_target: false
    place_target: true